#ifndef MDT_ERROR_TYPES_H__
#define MDT_ERROR_TYPES_H__


#define ENUM_TO_CASE_STRING(case_id)\
	case case_id:\
		return #case_id;

#define ENUM_TO_STRING(enum_id)		#enum_id

const char * __stdcall MDT_ErrorStatusToString(int status);


typedef enum
{
	//Default error
	MDT_UNKNOW_ERROR = -1,
	MDT_OK = 0,

	//Link Map File Error==>Search file error
	MDT_SEARCH_SCATTER_ERROR = 1000,
	MDT_NONE_SCATTER_IS_FOUND,
	MDT_TOO_MANY_SCATTER_FILE,
	MDT_INVALID_FOLDER_PATH,

	//Link Map File Error==>Load Image Error
	MDT_SAME_FLASHID_AND_BBCHIP_SW_VER,
	MDT_CREATE_DL_HANDLE_FAIL,
	MDT_GET_LOADED_ROM_COUNT_FAIL,
	MDT_GET_ROM_INFO_ALL_FAIL,
	MDT_GET_TOO_MANY_ROM,
	MDT_CAN_NOT_LOAD_ALL_IMAGES,
	MDT_QUERY_FLAHS_TYPE_ERROR,
	MDT_LOAD_EXTENSION_BOOTLOADER_FAIL,
	MDT_LOAD_BOOTLOADER_FAIL,
	MDT_GET_BOOTLOADER_INFO_FAIL,
	MDT_ENABLE_BOOTLOADER_FAIL,
	MDT_MORE_THAN_ONE_SEC_RO,
	MDT_LOAD_SEC_RO_FILE_FAIL,
	MDT_ADD_DL_HANDLE_TO_HANDLE_LIST_FAIL,

	MDT_INI_FILE_IS_INVALID,
	MDT_INVALID_DOWNLOAD_HANDLE,

	//==========================================
	MDT_SV5_INVALID_CONFIGFILE,
	MDT_SV5_LOAD_ROM_FILES_ERROR,
		
	//==========================================
	MDT_SV5_UNKNOWN_ERROR,
	MDT_SV5_EFUSE_WRITER_INVALID_FILE,
	MDT_SV5_EFUSE_WRITER_INVALID_SETTING_FILE,
	MDT_SV5_EFUSE_WRITER_INVALID_LOCK_FILE,
	MDT_SV5_EFUSE_WRITER_INVALID_POINTER,	
	MDT_SV5_EFUSE_WRITER_INVALID_LOCK_SETTING,
	MDT_SV5_EFUSE_WRITER_IS_NOT_READY,
	MDT_SV5_EFUSE_WRITER_INVALID_PARAMETER,
	MDT_SV5_EFUSE_WRITER_OUTOF_MEMROY,
	MDT_SV5_EFUSE_WRITER_ALL_COMMON_REGISTER_SETTING_ERROR,
	MDT_SV5_EFUSE_WRITER_ALL_SECURE_REGISTER_SETTING_ERROR,
	MDT_SV5_EFUSE_WRITER_COMMON_LOCK_REGISTER_NOT_MATCH,
	MDT_SV5_EFUSE_WRITER_SECURE_LOCK_REGISTER_NOT_MATCH,
	MDT_SV5_EFUSE_WRITER_SETTING_FILE_IS_NULL,
	MDT_SV5_EFUSE_WRITER_LOCK_FILE_IS_NULL,
	MDT_SV5_EFUSE_WRITER_WRITE_SETTING_IS_NOT_READY,
	MDT_SV5_EFUSE_WRITER_LOCK_SETTING_IS_NOT_READY,

	
	

	MDT_CUSTOM_ERROR_STATUS,


	MDT_ERROR_STATUS_END

}MDT_ERROR_STATUS;



#endif

