#include "mdt_component/error_handler/inc/MDT_ErrorTypes.h"




const char * __stdcall MDT_ErrorStatusToString(int status)
{
	switch(status)
	{
		ENUM_TO_CASE_STRING(MDT_OK)
			//Link Map File Error==>Search file error
		ENUM_TO_CASE_STRING(MDT_SEARCH_SCATTER_ERROR)
		ENUM_TO_CASE_STRING(MDT_NONE_SCATTER_IS_FOUND)
		ENUM_TO_CASE_STRING(MDT_TOO_MANY_SCATTER_FILE)
		ENUM_TO_CASE_STRING(MDT_INVALID_FOLDER_PATH)
		
		//Link Map File Error==>Load Image Error
		ENUM_TO_CASE_STRING(MDT_SAME_FLASHID_AND_BBCHIP_SW_VER)
		ENUM_TO_CASE_STRING(MDT_CREATE_DL_HANDLE_FAIL)
		ENUM_TO_CASE_STRING(MDT_GET_LOADED_ROM_COUNT_FAIL)
		ENUM_TO_CASE_STRING(MDT_GET_ROM_INFO_ALL_FAIL)
		ENUM_TO_CASE_STRING(MDT_GET_TOO_MANY_ROM)
		ENUM_TO_CASE_STRING(MDT_CAN_NOT_LOAD_ALL_IMAGES)
		ENUM_TO_CASE_STRING(MDT_QUERY_FLAHS_TYPE_ERROR)
		ENUM_TO_CASE_STRING(MDT_LOAD_EXTENSION_BOOTLOADER_FAIL)
		ENUM_TO_CASE_STRING(MDT_LOAD_BOOTLOADER_FAIL)
		ENUM_TO_CASE_STRING(MDT_GET_BOOTLOADER_INFO_FAIL)
		ENUM_TO_CASE_STRING(MDT_ENABLE_BOOTLOADER_FAIL)
		ENUM_TO_CASE_STRING(MDT_MORE_THAN_ONE_SEC_RO)
		ENUM_TO_CASE_STRING(MDT_LOAD_SEC_RO_FILE_FAIL)
		ENUM_TO_CASE_STRING(MDT_ADD_DL_HANDLE_TO_HANDLE_LIST_FAIL)
		
		ENUM_TO_CASE_STRING(MDT_INI_FILE_IS_INVALID)
		ENUM_TO_CASE_STRING(MDT_INVALID_DOWNLOAD_HANDLE)
		
		//==========================================
		ENUM_TO_CASE_STRING(MDT_SV5_INVALID_CONFIGFILE)
		ENUM_TO_CASE_STRING(MDT_SV5_LOAD_ROM_FILES_ERROR)
			
		//==========================================
		ENUM_TO_CASE_STRING(MDT_SV5_EFUSE_WRITER_INVALID_SETTING_FILE)
		ENUM_TO_CASE_STRING(MDT_SV5_EFUSE_WRITER_INVALID_LOCK_FILE)
		ENUM_TO_CASE_STRING(MDT_SV5_EFUSE_WRITER_INVALID_POINTER)
		
		ENUM_TO_CASE_STRING(MDT_SV5_EFUSE_WRITER_INVALID_LOCK_SETTING)
		ENUM_TO_CASE_STRING(MDT_SV5_EFUSE_WRITER_IS_NOT_READY)
		ENUM_TO_CASE_STRING(MDT_SV5_EFUSE_WRITER_INVALID_PARAMETER)
		ENUM_TO_CASE_STRING(MDT_SV5_EFUSE_WRITER_OUTOF_MEMROY)
		
		
		ENUM_TO_CASE_STRING(MDT_SV5_EFUSE_WRITER_ALL_COMMON_REGISTER_SETTING_ERROR)
		ENUM_TO_CASE_STRING(MDT_SV5_EFUSE_WRITER_ALL_SECURE_REGISTER_SETTING_ERROR)
		ENUM_TO_CASE_STRING(MDT_SV5_EFUSE_WRITER_COMMON_LOCK_REGISTER_NOT_MATCH)
		ENUM_TO_CASE_STRING(MDT_SV5_EFUSE_WRITER_SECURE_LOCK_REGISTER_NOT_MATCH)
		
		
		
		
		
		ENUM_TO_CASE_STRING(MDT_CUSTOM_ERROR_STATUS)
		
		
		ENUM_TO_CASE_STRING(MDT_ERROR_STATUS_END)

		default:
			return "Unknown Error";
	}


}







